Use customer_behaviour;
select * from customer_behaviour;

#1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer_behaviour
group by gender;

#2 which customers used a discount but still spent more than average purchase amount
select customer_id, purchase_amount from
customer_behaviour where discount_applied='Yes' and 
purchase_amount >= (select avg(purchase_amount) as avg_amount from customer_behaviour);

#3 which are the top 5 products with the highest average review rating?
select  item_purchased, avg(review_rating) as avg_rating
from customer_behaviour
group by item_purchased order by avg_rating desc limit 5;

#4 Compare the average purchase amount between standard and expression shipping?
select shipping_type, avg(purchase_amount)
from customer_behaviour
where shipping_type in ('Standard','Express')
group by shipping_type;

#5 Do subscribed customers spend more? compare average revenue spend and total revenue between subscribers and non subscribers?
select subscription_status, count(customer_id) as total_customers,avg(purchase_amount) as avg_spend,
Round(sum(purchase_amount)) as total_revenue
from customer_behaviour
group by subscription_status
order by total_revenue, avg_spend desc;

#6 which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round (100* sum(case when discount_applied='Yes' Then 1 else 0 end)/count(*), 2) as discount_rate
from customer_behaviour
group by item_purchased
order by discount_rate desc limit 5;

#7 segment customers into new, returning, and loyal based on their total number of previous purchases, and
# and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases=1 Then 'New'
    When previous_purchases between 2 and 10 Then 'Returning'
    else 'Loyal'
    end as customer_segment
    from customer_behaviour
    )
    select customer_segment, count(*) as 'Number of customers'
    from customer_type
    group by customer_segment;
    
#8 what are the top 3 most purchased products within each category?

with item_count as(
select category, item_purchased,count(customer_id) as total_orders,
Row_number() over (partition by category
order by count(customer_id) desc) as item_rank
from customer_behaviour
group by category,item_purchased
)
select item_rank,category,item_purchased, total_orders
from item_count
where item_rank<=3;

#9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers from customer_behaviour
where previous_purchases>5
group by subscription_status;

#10 what is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer_behaviour
group by age_group
order by total_revenue desc;


















